server {
    listen 80;

    # 1. Serve Vite Dev Client (Lit App web server)
    location / {
        proxy_pass http://frontend-build:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    # 2. Route Frontend Development reloads (HMR)
    location /vite-hmr {
        proxy_pass http://frontend-build:5173/vite-hmr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    # 3. Route Your Custom WebSocket Server App
    location /ss {
        proxy_pass http://websocket-server:8000; # Address of your backend server
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}
