server {
    listen 80;
    server_name pexera.online;
    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name pexera.online;

    # Point these to the absolute paths inside the container
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # 1. Frontend Web App Subdirectory
    location /arx/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /arx/index.html;
    }

    # 2. WebSockets Signaling Server
    location /arx/ss {
        proxy_pass http://signaling-server:8080; # Matches the compose service name
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Disable timeouts for persistent WebSockets connections
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
